"""empty message

Revision ID: 0565465a155e
Revises: 24e827b712b5
Create Date: 2022-07-26 15:03:06.264038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0565465a155e'
down_revision = '24e827b712b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('ingredient_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredient_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('recipe',
    sa.Column('recipe_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_name', sa.String(), nullable=False),
    sa.Column('recipe_description', sa.String(), nullable=False),
    sa.Column('recipe_instructions', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.ingredient_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredients')
    op.drop_table('recipe')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
