"""empty message

Revision ID: 24e827b712b5
Revises: 
Create Date: 2022-07-26 13:50:27.824921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e827b712b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('location',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('mold',
    sa.Column('mold_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('well_shape', sa.String(), nullable=False),
    sa.Column('well_volume', sa.Integer(), nullable=False),
    sa.Column('num_wells', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('mold_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mold')
    op.drop_table('location')
    op.drop_table('category')
    # ### end Alembic commands ###
