"""empty message

Revision ID: 769702bf4c98
Revises: 1669038a6b95
Create Date: 2022-07-27 14:15:02.095532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769702bf4c98'
down_revision = '1669038a6b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mold', sa.Column('well_volume_grams', sa.Integer(), nullable=False))
    op.drop_column('mold', 'well_volume')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mold', sa.Column('well_volume', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('mold', 'well_volume_grams')
    # ### end Alembic commands ###
